.gitignore, data.tf, diagnostics.tf, frontdoor.tf, frontdoor_kv_access.tf, frontdoor_waf_policy.tf, provider.tf, variables.tf
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> Files are copied from original repo

README.md, diagnostics.tf, variables.tf
https://tools.hmcts.net/jira/browse/DTSPO-420
Passing Log workspace id details
=> dtspo420: passing log workspace id

provider.tf
https://tools.hmcts.net/jira/browse/DTSPO-242
[ ] Yes
[ x] No
```
=> dtspo242: Removed "data" provider 

frontdoor.tf
Temporarily commenting our 4hr timeout on the frontdoor config.
```
[ ] Yes
[x] No
```
=> DTSPO-75 - removing timeout as the apply is taking over 4 hours

frontdoor.tf
Removed timeouts for frontdoor, the default timeout is 6 hours.
```
[ ] Yes
[x] No
```
=> DTPOS-75 - deleted timeouts for frontdoor

frontdoor.tf
Changing backend http port to allow alternative values when this module is called.
=> Dtspo 1783 creating default http port lookup

frontdoor.tf
=> Fix case of firewall policy

frontdoor_waf_policy.tf
https://tools.hmcts.net/jira/browse/DTSPO-1727
Update to apply tags to WAF policies.
```
[ ] Yes
[x ] No
```
=> DTSPO-1727 Apply tags to WAF Policies

providers.tf, validation/fd.tf, validation/provider.tf
Seems to have been left over from when log analytics had a datasource in here
=> Remove unneeded provider

frontdoor.tf, variables.tf
=> DTSPO-2980 session affinity

azure_pipeline.yaml
=> Upgrade Terraform to 0.15.4

frontdoor.tf, frontdoor_kv_access.tf, providers.tf
https://tools.hmcts.net/jira/browse/DTSPO-10835
Upgrade azurerm to 3.34
```
[ ] Yes
[x] No
```
=> DTSPO-10835 - update provider to 3.34

frontdoor.tf
=> Enable health only for multiple backend domains

diagnostics.tf, variables.tf
Add the capability to send access logs to storage account to save a lot of money
=> Adjust FrontDoor diagnostics

frontdoor.tf, locals.tf, providers.tf
https://tools.hmcts.net/jira/browse/DTSPO-15720
This change will allow to add the TXT record to the DNS zone and verify the frontend
=> DTSPO-15720 - Add validation token

frontdoor.tf
https://tools.hmcts.net/jira/browse/DTSPO-14559
Updating module to fix errors with txt record creation
=> DTSPO-14559 - TXT validation

frontdoor.tf
https://tools.hmcts.net/jira/browse/DTSPO-14559
Change front door secrets to use latest version (versionless) so they update automatically when acme certs are renewed
=> DTSPO-14559 - cdn secret versionless

frontdoor_waf_policy.tf
https://tools.hmcts.net/jira/browse/DTSPO-16416
* add optional 'selector' param for match_variable 'PostArgs' custom WAF rule
* needed to implement custom rule for above ticket
=> add optional 'selector' param for match_variable 'PostArgs' custom WAF rule

frontdoor.tf
https://tools.hmcts.net/jira/browse/DTSPO-16863
Change name of second origin as duplicates
=> Change name of second origin

frontdoor.tf, frontdoor_waf_policy.tf, locals.tf, rules.tf
https://tools.hmcts.net/jira/browse/DTSPO-15970
Changes has been tested on sds-azure-platform
https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=590535&view=results
=> DTSPO-15970 - Added option to cache static files using ruleset

providers.tf
Reverts hmcts/terraform-module-frontdoor#56
=> Revert "Update Terraform azapi to v2"

frontdoor_waf_policy.tf
https://tools.hmcts.net/jira/browse/PUB-2679
Update module to allow for handling of different firewall versions
=> PUB-2679 - Added ability for different firewall versions

frontdoor_waf_policy.tf
https://tools.hmcts.net/jira/browse/PUB-2727
Allow override of disabled rule action for ruleset version of 2.0 and 2.1
=> PUB-2727 Allow override of disabled rule action for ruleset version of 2.0 and 2.1

frontdoor_waf_policy.tf
https://tools.hmcts.net/jira/browse/DTSPO-23355
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
adding FD policy condition to allow RequestHeader match variable
=> adding FD policy condition to allow RequestHeader match variable
